#!/usr/bin/env bash
"""Bash script that pings an IP address passed as an argument."""


if [ -z "$1" ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

echo "PING $ip_address"

for (( i=1; i<=5; i++ )); do
  ping -c 1 "$ip_address"
done